apiVersion: v1
kind: Service
metadata:
  name: rsvp
  namespace: rsvp-app
  labels:
    app: rsvp
spec:
  type: NodePort
  selector:
    app: rsvp
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080