apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-script
  namespace: rsvp-app
data:
  init-db.js: |
    db.createUser({
      user: 'rsvpadm',
      pwd: 'hodi',
      roles: [{ role: 'readWrite', db: 'rsvp' }]
    });